### ISSUE TITLE
Link to the documentation in README.md is broken.

### ISSUE THREAD

**Issue by zoomacode** [TolokaAI/toloka-kit#3]
The link https://yandex.ru/dev/toloka/doc/concepts/about.html?lang=en leads to 404 page.

**Comment by ortemij** [comment]
Could you pls provide some details, e.g., a screenshot, cause it works for me.

**Comment by zoomacode** [comment]
It works well now. I probably faced one of those moments when toloka documentation return 404 for a minute or so.

**Comment by ortemij** [comment]
Okay, we'll try to reproduce this by ourselves. Thank you for the report!
